### PR TITLE
updated repo

### PR DESCRIPTION
**Pull request by uweschmitt**
New public release of current project

@chaoran-chen can you please check if I addes  sth which is not specific for `S3C`?

### CODE REVIEW

**Comment by john-hen** [comment]
@uweschmitt This is a single commit, when we should be able to fast-forward the `public` branch here to current `main` of the internal repo. I want proper name attribution.

**Comment by uweschmitt** [comment]
@john-hen I know, we had a discussion today, and apparently nobody is interested in keeping a history. A snapshot is much easier to check for accidentally committed secrets etc than checking and fixing a whole history for passwords, servernames, folder names on euler etc. Nobody volunteered to take such a task.

**Comment by john-hen** [comment]
Then we should not publish. This infringes on authors' rights.

**Comment by uweschmitt** [comment]
Will close this request until further clarification.

**Pull request closed without merging**
